# Generated by Django 3.2.9 on 2021-11-07 16:06

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cantidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('unidad', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=1000)),
                ('tiempo', models.IntegerField(default=0)),
                ('tipo', models.CharField(choices=[(myapp.models.TipoReceta['D'], 'Desayuno'), (myapp.models.TipoReceta['A'], 'Aperitivo'), (myapp.models.TipoReceta['CO'], 'Comida'), (myapp.models.TipoReceta['M'], 'Merienda'), (myapp.models.TipoReceta['CE'], 'Cena')], max_length=50)),
                ('duracion', models.CharField(choices=[(myapp.models.DuracionReceta['MR'], 'Muy rapido'), (myapp.models.DuracionReceta['R'], 'Rapido'), (myapp.models.DuracionReceta['M'], 'Medio'), (myapp.models.DuracionReceta['L'], 'Lento'), (myapp.models.DuracionReceta['ML'], 'Muy lento')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('calorias', models.IntegerField(default=0)),
                ('cantidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cantidad')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.receta')),
            ],
        ),
        migrations.AddField(
            model_name='cantidad',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.receta'),
        ),
    ]
