# Generated by Django 3.2.8 on 2021-11-08 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DuracionReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('calorias', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TipoReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=10000)),
                ('tiempo', models.IntegerField(default=0)),
                ('duracion', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.duracionreceta')),
                ('tipo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.tiporeceta')),
            ],
        ),
        migrations.CreateModel(
            name='Cantidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0)),
                ('unidad', models.CharField(max_length=40)),
                ('ingrediente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.ingrediente')),
                ('receta', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.receta')),
            ],
        ),
    ]
