# Generated by Django 3.2.9 on 2021-11-07 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='receta',
        ),
        migrations.AddField(
            model_name='cantidad',
            name='ingrediente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.ingrediente'),
        ),
        migrations.AlterField(
            model_name='cantidad',
            name='receta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.receta'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='duracion',
            field=models.CharField(choices=[('MR', 'Muy rapido'), ('R', 'Rapido'), ('M', 'Medio'), ('L', 'Lento'), ('ML', 'Muy lento')], max_length=50),
        ),
        migrations.AlterField(
            model_name='receta',
            name='tipo',
            field=models.CharField(choices=[('D', 'Desayuno'), ('A', 'Aperitivo'), ('CO', 'Comida'), ('M', 'Merienda'), ('CE', 'Cena')], max_length=50),
        ),
    ]
